apiVersion: apps/v1
kind: Deployment
metadata:
  name: easyrent-app-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easyrent-app-prod
  template:
    metadata:
      labels:
        app: easyrent-app-prod
    spec:
      containers:
        - name: easyrent-app-prod
          image: gcr.io/constellation-275522/easyrent-app
          ports:
            - containerPort: 80
          resources:
            limits:
              cpu: ".5"
              memory: "500Mi"
            requests:
              cpu: ".25"
              memory: "250Mi"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: easyrent-app-prod-nodeport
spec:
  selector:
    app: easyrent-app-prod
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: easyrent-app-prod-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: easyrent-app-prod
    networking.gke.io/managed-certificates: easyrent-app-prod-certificate
#    kubernetes.io/ingress.allow-http: "false"
spec:
  backend:
    serviceName: easyrent-app-prod-nodeport
    servicePort: 80
---
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: easyrent-app-prod-certificate
spec:
  domains:
    - easyrent.citwdd.net
